### PR TITLE
Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by afmachado**

### CODE REVIEW

**Comment by mkulesh** [comment]
Dear @afmachado, thank you for this translation, I merged it. I did not found translated doc_br/how_to_use.xml. Is there any chance to translate it as well? 

I also added today a new string. How does it in Portuguese: "Export screenshots"

I would like to add your name in the README file of the repository and in the about_micromath.xml.
If you agree, please tell me your full name and email.

**Comment by mkulesh** [comment]
Language names are also not translated:
    <string-array name="language_names">
        <item>English</item>
        <item>Russian</item>
        <item>German</item>
        <item>Brazilian Portuguese</item>
    </string-array>

**Comment by mkulesh** [comment]
Sorry, "Export screenshots" is already translated, the Android Studio just hide it from unknown reason...

**Comment by mkulesh** [comment]
Dear @afmachado, please check newly generated APK https://github.com/mkulesh/microMathematics/blob/master/release/microMathematics-v2.15.4a.apk 
that contains now your translation.

**Comment by afmachado** [comment]
I am still translating the how_to_use doc.
My full name is Caio Roberto Ramos da Silva
email caiorrs@gmail.com

**Comment by mkulesh** [comment]
Dear @afmachado, do you have any estimates when the translating of how_to_use can be finished? I ask since I plan to make the next release soon and, I think, it is not a good idea to release something that have in incomplete translation.

**Comment by afmachado** [comment]
hey, sorry. I have been really busy translating other applications, and with college stuff. Giving you an estimate, probably until saturday. The how to use file is big. Oh, and may I ask why you used the &#10; to format the texts? Those are really painful when translating =P

**Pull request merged**
