### PR TITLE
Starting a french translation

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by mkulesh** [comment]
Dear @RyDroid, please update your branch since I fixed some compiler error for the french translation that you merged.

**Comment by mkulesh** [comment]
Dear @RyDroid, do you have any chance to finish french translation within next two weeks? I just plan a new release soon...

**Comment by RyDroid** [comment]
I remember that I did the easiest part last time, so I do not know if I will be able to 100% finish (I am French but I do not use English in my daily life, except for programming).

**Comment by mkulesh** [comment]
Dear @RyDroid, thank you for pull request, I merged it. Please update your branch since I fixed some compiler errors in the translation and added some new strings. I also opened a new issue #23 in order to trace these activities. 

Please make a list of points like "Embedded image" within the issue #23 (this is hard to translate without knowing the context), I will than explain them. 

"Embedded image" in the context of the App means: include the image into the worksheet instead to reference it in the file system.

**Pull request merged**
