### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by sguinetti**
This is the Spanish translation of the app, both the strings.xml file and the "doc_es" folder.

### CODE REVIEW

**Comment by mkulesh** [comment]
Hi @sguinetti,
thank you for the pull request. I merged it and will deploy in the next version.

**Comment by mkulesh** [comment]
Hi @sguinetti,
I would like to add your name on the project page and in the About page ("Author" list). Could you please provide me your name and email for it? (better on mikhail.kulesh@gmail.com)

**Comment by mkulesh** [comment]
Hi @sguinetti 
I build PDF in Spanish (https://github.com/mkulesh/microMathematics/blob/supplement/doc/microMathematics-v2.20.0-es.pdf) and activated all Spanish resources in the app. Could you please install the latest nightly build (https://github.com/mkulesh/microMathematics/blob/autobuild/autobuild/microMathematics-v2.20.0-debug.apk) and check whether the translation is OK?

**Comment by sguinetti** [comment]
I thank you for this initiative. But personally I don't usually use the mail. Would the name "Diego Sanguinetti" be enough? 

About the PDF that was generated I see that it is translated into Portuguese (br) instead of Spanish (es). Do you have any recommendations so that I can correct it?

**Comment by mkulesh** [comment]
Hi @sguinetti, thank you for replay. No problem to add your name without mail. I added "Diego Sanguinetti" in all related documents (and also on the main project page here on github).
Thank you for the report about wrongly generated PDF. My bug. Now it is fixed. The file https://github.com/mkulesh/microMathematics/blob/supplement/doc/microMathematics-v2.20.0-es.pdf shall now contain the correct language. 

The PDF is generated from *.mmt files that you added in your pull request. The simplest way is that you directly edit these files if necessary. I will than just re-generate PDF.

**Comment by sguinetti** [comment]
Thank you @mkulesh. You've been very kind. The PDF is acceptable for now. In a few days, In next day, I review some details of the APK debug.

**Pull request merged**
