### PR TITLE
Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by mkulesh** [comment]
Hi @linsui, thanks for the translation. I merged your change and will try to prepare new release shortly. Sorry for the delay with your merge.

**Comment by mkulesh** [comment]
New build that contains your merge is now available:
https://github.com/mkulesh/microMathematics/raw/autobuild/autobuild/microMathematics-v2.17.3.apk
Please inspect whether there are any conflicts with other Chinese translation (currently, there are Traditional and Simplified translations)

**Comment by mkulesh** [comment]
Dear @linsui, I would like to add you in the contributor list in the app and main github page. If it is OK for you, could you please provide me you name and e-mail?

**Comment by linsui** [comment]
I have test the build and it works well. 👍 
Thanks, my name is linsui and e-mail is linsui555@gmail.com. 😄

**Pull request merged**
